name: trunk

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [12.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.3.0
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm run -s build
      - run: pnpm run -s test


  release-canary:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.3.0
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Release Canary
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          pnpm run -s dripip preview --json > result.json
          jq '.' < result.json
